#tools=["Bill Of Materials", "Cobra", "ErrorProne", "Open Source Vulnerabilities", "Semgrep", "refactor-first"]

# works
#tools=["ErrorProne", "Cobra"]

# does not work
#tools=["ErrorProne", "Cobra", "FindSecBugs"]

# Failed
#tools=["ErrorProne", "Cobra", "Infer"]

# Failed
#tools=["Cobra", "Infer"]

tools=["Infer"]

